---
- hosts: vm05
  become: yes
  roles:
    - joe_speedboat.ansible_otrs
  vars:
    otrs_rpm_url: http://ftp.otrs.org/pub/otrs/RPMS/rhel/6/otrs-3.3.9-01.noarch.rpm
  tasks:
  # - debug: var=mariadb_mysqld_config
  - name: install firewalld
    yum:
      name: firewalld
      state: present
  - name: start firewalld
    service:
      name: firewalld
      enabled: yes
      state: started
  - name: open http port on firewalld
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: open https port on firewalld
    firewalld:
      service: https
      permanent: true
      state: enabled
  - name: enable firewalld
    service:
      name: firewalld
      enabled: yes
      state: restarted
...
