---
# handlers file for joe_speedboat.ansible_otrs

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: restart crond
  service:
    name: crond
    state: restarted
...
